name: CI/CD for Wisecow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rkravichennai7/wisecow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, windows, minikube]   # <- match your runner labels
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
          # On Windows runner, kubectl may already be installed; keep this if not.
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure kubeconfig (from secret)
        shell: pwsh
        run: |
          $b64 = "${env:KUBECONFIG_B64}"
          [IO.File]::WriteAllBytes("$env:RUNNER_TEMP\kubeconfig", [Convert]::FromBase64String($b64))
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Deploy manifests
        shell: pwsh
        env:
          KUBECONFIG: ${{ runner.temp }}\kubeconfig
        run: |
          kubectl apply -f k8s/cert-issuer.yaml || exit 0
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl rollout status deployment/wisecow --timeout=120s
